@extends('front.master')

@section('metaDescription')
@endsection


@section('title')
    About Us | Phone List
@endsection

@section('main')
    <!-- START BREADCRUMB -->
    <hr class="mt-lg-0 mt-5 text-secondary" />
    <div class="container">
        <div class="row">
            <nav style="--bs-breadcrumb-divider: '>'" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('/') }}">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">
                        {{$file_name}}
                    </li>
                </ol>
            </nav>
        </div>
    </div>
    <!-- END BREADCRUMB -->
    

    <!-- START SITEMAP HEADING -->
    <section class="section-sitemap-heading u-padding-lg">
        <div class="container">
          <div class="row">
            <div class="col-md-12 text-center">
              <h1>XML Sitemap</h1>
              <p class="section-text w-75 mx-auto my-5">
                Generated by <a href="https://phonelist.io/">Phonelist</a>, this
                is an XML Sitemap, meant for consumption by search engines. You
                can find more information about XML sitemaps on
                <a href="https://sitemaps.org/">sitemaps.org</a> <br />
                This sitemap contains @if(count($fileData) > 0) {{count($fileData['url'])}} @else  0 @endif URLs.
              </p>
            </div>
          </div>
        </div>
      </section>
      <!-- END SITEMAP HEADING -->

      <!-- START SITEMAP TABLE -->
      <section class="section-sitemap-table u-padding-lg">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <table class="table">
                <thead>
                  <tr>
                    <th>Sitemap</th>
                    <th>Priority</th>
                    <th>Last Modified</th>
                    <th>Frequency</th>
                  </tr>
                </thead>
                <tbody>
                    @if (count($fileData) > 0)
                        @foreach ($fileData['url'] as $data)
                            <tr>
                                <td scope="row">
                                  <a href="{{ $data['loc'] }}">{{ $data['loc'] }}</a>
                                </td>
                                <td>{{ ($data['priority'] * 100) }}%</td>
                                <td>{{ date('d-m-Y h:i:s', strtotime($data['lastmod'])) }}</td>
                                <td>{{ $data['changefreq'] }}</td>
                            </tr>
                        @endforeach
                    @endif
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </section>
      <!-- END SITEMAP TABLE -->

@endsection
