@extends('front.master')

@section('metaDescription')
@endsection


@section('title')
    About Us | Phone List
@endsection

@section('main')
    <!-- START BREADCRUMB -->
    <hr class="mt-lg-0 mt-5 text-secondary" />
    <div class="container">
        <div class="row">
            <nav style="--bs-breadcrumb-divider: '>'" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('/') }}">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">
                        Sitemap
                    </li>
                </ol>
            </nav>
        </div>
    </div>
    <!-- END BREADCRUMB -->
    <!-- START SITEMAP HEADING -->
    <section class="section-sitemap-heading u-padding-lg">
        <div class="container">
          <div class="row">
            <div class="col-md-12 text-center">
              <h1>XML Sitemap</h1>
              <p class="section-text w-75 mx-auto my-5">
                Generated by <a href="https://phonelist.io/">Phonelist</a>, this
                is an XML Sitemap, meant for consumption by search engines. You
                can find more information about XML sitemaps on
                <a href="https://sitemaps.org/">sitemaps.org</a>
              </p>
            </div>
          </div>
        </div>
      </section>
      <!-- END SITEMAP HEADING -->

      <!-- START SITEMAP TABLE -->
      <section class="section-sitemap-table u-padding-lg">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <table class="table">
                <thead>
                  <tr>
                    <th>Sitemap</th>
                    <th>Last Modified</th>
                  </tr>
                </thead>
                <tbody>
                    @foreach ($files as $file)
                    <tr>
                        <td scope="row">
                          <a href="{{url('file-details/'.$file['name']) }}">{{$file['name']}}</a>
                        </td>
                        <td>{{$file['modified']}}</td>
                      </tr>
                    @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </section>
      <!-- END SITEMAP TABLE -->

@endsection
